export default {
    closeModalButton: document.getElementById('modal-close'),
    backdrop: document.querySelector('.js-backdrop'),
    container: document.querySelector('.js-container'),
    list: document.getElementById('filterElem'),
    modal: document.getElementById('modal'),
    input: document.getElementById('search-input'),
    modalBtnSubmit: document.querySelector('#modalSubmit'),
    // headerInput: document.getElementById('header-input'),
    // searchInput: document.getElementById('search-input'),
    modalBtnCancel: document.querySelector('#cancelBtn'),
    MAX_PILLS: 70,
    idNumbers: [],
    COLORS: ['white', 'green', 'orange', 'red'],
};
